### ISSUE TITLE
Pickling client objects is explicitly not supported (Iterable Dataset)

### ISSUE THREAD

**Issue by SkanderBS2024** [GoogleCloudPlatform/dataflux-pytorch#58]
Hello,

I've been running the following function which loads data from a bucket containg (1 txt and 2csv files)

<img width="880" alt="Capture d’écran 2024-07-16 à 14 45 10" src="https://github.com/user-attachments/assets/04c125d8-eb26-4de6-933d-e7d89c3eaae4">

And here is the main app logic :

<img width="751" alt="Capture d’écran 2024-07-16 à 14 45 39" src="https://github.com/user-attachments/assets/dbe5a861-40b9-440d-a5c9-7703fa610854">

 eveything seems to work fine when loading data and prints successfully the number of objects, but i'm getting 2 different errors,
one error related to the "dataflux_iterable_dataset" class which is the following : 

<img width="776" alt="Capture d’écran 2024-07-16 à 14 48 56" src="https://github.com/user-attachments/assets/8517a7dd-d3c7-4011-9454-9cbf1bbb996f">

i don't know why it's trying to delete the files after the code execution (and prints the number of objects succesfully), but it's not having the permission to delete (NOTE : with the "dataflux_mapstyle_dataset" i do not encounter this issue).

And the other error is related to the "data.DataLoader" from the pytorch module when i try to print the batches (the testing loop i've written above).

<img width="545" alt="Capture d’écran 2024-07-16 à 14 51 14" src="https://github.com/user-attachments/assets/d6fdb9d2-0aff-4238-a4fe-64ddb1dbe205">

Any solutions to this ?

**Comment by MattIrv** [comment]
Thanks for reporting this. 

For the first issue, Dataflux uses a "composed-download" algorithm (documented [here](https://github.com/GoogleCloudPlatform/dataflux-pytorch?tab=readme-ov-file#composite-objects)) for small files where it merges small files together into a larger temporary file, downloads the temporary file, and then deletes the temporary file. It looks like you don't have permission for delete, which is causing problems. If you have a low number of files or performance is not a concern, you can disable this behavior by setting the config as documented in that link. Alternatively, you can make sure you have object delete permission on the bucket you're working with. It's not immediately clear to me why you're not hitting this with the map-style data set as well - maybe I'd need to see a version of your `load_dataset` code to understand better.

I'll also look into whether it's possible for the code to automatically detect that it doesn't have the right permissions for compose/delete and automatically disable that behavior if so.

For the second issue, I will keep looking into it and try to reproduce the issue and share an update. @SkanderBS2024 can you confirm what platform you're running on? Are you using Windows?

**Comment by SkanderBS2024** [comment]
Oh i see that's why there is a new folder in the bucket "dataflux-composed-objects" which contains multiple files (global size of the origin files in the bucket for each). Yes indeed i did not set permission for delete in the bucket (for security purposes) and i thought it was deleting the origin files, but this only occurs for the "DataFluxIterableDataset".

Well honestly for the "why i'm not using map-style", i'm still testing the dataflux and i still don't know if it's a good fit for my use-case because i will be training a large model (over 500gb of data), so i guess i have to split all this data to small samples on different buckets (or maybe the same) ? Is it efficient for this amount of data ? is it better choice than FUSE ?
So that's why i'm going with the iterable because of the amount of data, and the data is not indexable.

here is the load_dataset function, a simple one, DataFluxConfig is a new class inherited form the main dataflux configuration in order to customize it easly in a separate module that contains my configurations.
Read_text_modified also a basic function to process the data.

<img width="1002" alt="Capture d’écran 2024-07-16 à 22 29 14" src="https://github.com/user-attachments/assets/d457b7c9-22a6-45bc-8915-ada086174fad">

Assuming that in the bucket there is a total of 3 files (1 txt and 2csv) i was wondering how dataflux reads them (should i have a specified format ? does it have a generic file parser or something ?

I've managed to take a look at the dataset content this way (which prints the processed data correctly, with the DELETE error) :

<img width="732" alt="Capture d’écran 2024-07-16 à 22 36 29" src="https://github.com/user-attachments/assets/44e2fdf7-f23d-477a-9d8b-0223841e32f6">

But normally with the other approach it should work right ?

And finally for the platform i'm running on MacOS Sonoma 14.3 (M1 chip).
Thank you for your asistance @MattIrv

**Comment by MattIrv** [comment]
@SkanderBS2024 thanks for the additional details. Is there a stack trace with the `PicklingError` that you'd be able to share?

With regard to performance and comparison to FUSE, Dataflux is going to have the most benefit vs. FUSE if your data in GCS consists of many very small objects (typically < 1 MB, see our [performance numbers](https://github.com/GoogleCloudPlatform/dataflux-pytorch?tab=readme-ov-file#performance)) because then you'll be able to take advantage of the composed-download functionality.

If your objects are bigger than this, then we do expect roughly similar performance to FUSE, but it's going to depend on the exact size of objects and pattern of access. 

For generic parsing and handling txt/csvs, Dataflux's default dataset assumes that each object in your bucket is one item for your batch, and doesn't do any sort of parsing on its own. If that's not the case, you'd need to pass a custom [data_format_fn](https://github.com/GoogleCloudPlatform/dataflux-pytorch/blob/main/dataflux_pytorch/dataflux_mapstyle_dataset.py#L94) to the dataset in order to process the object, or create your own Dataset implementation using the underlying list and download algorithms, like we've done in [this demo](https://github.com/GoogleCloudPlatform/dataflux-pytorch/blob/main/demo/image-segmentation/pytorch_loader.py#L252).

**Comment by SkanderBS2024** [comment]
Sure, here is the traceback (something related to multi-processing with the google cloud client)

<img width="997" alt="Capture d’écran 2024-07-16 à 23 00 27" src="https://github.com/user-attachments/assets/25ac4d65-1fac-4be3-aaec-511f3d65cf9c">

and does it support large files without any problems or there is a limit ? (it was around 200mb for FUSE for an efficient use i think), and as i've understood there is no data limit (and probably better than local storage loading on the VM?)

**Comment by MattIrv** [comment]
For large files, the only limitation is that it is going to load the whole object into memory when downloading it, so your memory will need to be large enough to hold `num_workers * batch_size * prefetch_factor` objects

**Comment by SkanderBS2024** [comment]
Okay so as i've understood it's more efficient for small size files but can handle. a large amount of them and still keep the good performance. Thank you for your assitance @MattIrv

**Comment by akansha1812** [comment]
@SkanderBS2024 We were able to reproduce the "PicklingError: Pickling client objects is explicitly not supported." issue on Mac. I was able to run it successfully on Linux.
Used code:
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/f1c411a0-2973-4073-899f-7aaacf964bcd">
We are looking into how we can resolve it for Mac.

**Comment by SkanderBS2024** [comment]
@akansha1812 Same code shared above :

<img width="775" alt="Capture d’écran 2024-07-22 à 1 47 09 PM" src="https://github.com/user-attachments/assets/670dab2c-faa2-4e13-90b8-abcd92c1aef5">

Working on a macbook pro M1 (16/256) and not working on a macbook pro M3 max (36/1tb):

Result in MBP M3 Max : 
<img width="540" alt="Capture d’écran 2024-07-22 à 1 48 25 PM" src="https://github.com/user-attachments/assets/20515ea7-688a-4d6e-afae-bc5ded51f999">

Result in MBP M1 :

<img width="834" alt="Capture d’écran 2024-07-22 à 13 49 16" src="https://github.com/user-attachments/assets/918fce23-e66b-459b-9178-0815901a82fa">

**Comment by akansha1812** [comment]
It seems like you can set num_workers=0, it worked for me. Can you please try this?

**Comment by akansha1812** [comment]
It seems like you can set num_workers=0 for pytorch dataLoader. This worked for me, can you please try this?
We are looking into how we can resolve it for parallel workers.

**Comment by akansha1812** [comment]
Multiprocessing doesn't fully support storage client when start method is spawn or forksever. In case of Mac it is mostly spawn.   

The pickling error is because dataflux_iterable_dataset.DataFluxIterableDataset was passing-in a client-storage while downloading objects even if the user does not pass in the storage client. 

This has been fixed from dataflux. In case of Mac, if `multiprocessing.get_start_method(allow_none=False)` is "spaw" or "forkserver", avoid passing in storage client.
